/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicCvAnalyzeRouteImport } from './routes/api.public.cv-analyze'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCvAnalyzeRoute = ApiPublicCvAnalyzeRouteImport.update({
  id: '/api/public/cv-analyze',
  path: '/api/public/cv-analyze',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/cv-analyze': typeof ApiPublicCvAnalyzeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/cv-analyze': typeof ApiPublicCvAnalyzeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/cv-analyze': typeof ApiPublicCvAnalyzeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/cv-analyze'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/cv-analyze'
  id: '__root__' | '/' | '/api/public/cv-analyze'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicCvAnalyzeRoute: typeof ApiPublicCvAnalyzeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cv-analyze': {
      id: '/api/public/cv-analyze'
      path: '/api/public/cv-analyze'
      fullPath: '/api/public/cv-analyze'
      preLoaderRoute: typeof ApiPublicCvAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicCvAnalyzeRoute: ApiPublicCvAnalyzeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
